/* CLASE MODELO QUE DEFINE LOS OBJETOS EN LOS SERVICIOS DEL FRONT QUE SE COMUNICAN CON EL BACK */
export class Carrito {

    _id: string;
    idUsuario: string;
    idJuegos: Array<string>;

    /* LOS CARRITOS Y LAS COMRPAS SE CREAN Y EDITAN MEDIANTE LA INSTANCIACIÓN DE UN OBJETO CARRITO QUE SE PASA AL BACK
    Y NO MEDIANTE UN FORMULARIO COMO PASA EN LOS USUARIOS O EN LOS JUEGOS. POR ESO NECESITAMOS UN CONSTRUCTOR.

    EL CONSTRUCTOR SOBRECARGARDO DE CARRITO RECIBE:
     - EL ID DEL USUARIO AL QUE PERTENECE EL CARRITO, CON EL QUE ESTAMOS LOGUEADOS
     - UN ARRAY DE IDS DE JUEGOS, QUE INICIALMENTE, DURANTE LA CREACIÓN DEL CARRITO, LO CREAMOS Y PASAMOS VACÍO
    */
    constructor(idUsuario: string, arrayJuegos : Array<string>) {
        this.idUsuario = idUsuario
        this.idJuegos = arrayJuegos
    }

}